# Generated by Django 4.2.7 on 2024-01-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_options_alter_categories_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='prouct',
        ),
    ]
