# Generated by Django 4.2.7 on 2024-01-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='product',
        ),
    ]
